//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/_Main/Inout/AstroneerCrafting/AC_CharacterInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AC_CharacterInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AC_CharacterInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AC_CharacterInputActions"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""45169b41-9b81-473b-9454-e4875d5a0ef7"",
            ""actions"": [
                {
                    ""name"": ""MovementAxis"",
                    ""type"": ""Value"",
                    ""id"": ""8a5f4f15-e31c-4576-a4fd-2fedba632118"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraAxis"",
                    ""type"": ""Value"",
                    ""id"": ""f45111d6-4c4c-46a1-9d77-588fa370e4c4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""99831ab0-b4c5-4efc-80e1-f36a1ae595e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""afb31c0b-a793-4393-a54d-e4fac0033d4f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c2a15ca0-ac3c-42a3-af1f-da3dbeb1780e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2200bd72-acf1-4d1a-940d-6aad46f7af1d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7864d02-39d1-4501-bb47-8e33b0aacf12"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""59c74488-e9a8-426b-9afe-dc05cfcf0d2d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""16d8c3a7-1d7d-40c8-81eb-6628b894f003"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MovementAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c7b6f10-c558-4362-896b-51e4fa527085"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0aaf2db-f081-4ea1-8b76-590063f96027"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c1aceba-b109-41d0-a478-52d9acafa4c9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Printer"",
            ""id"": ""0b75586b-5c1b-4263-b6bc-81a6732b26bc"",
            ""actions"": [
                {
                    ""name"": ""CycleRecipe"",
                    ""type"": ""Value"",
                    ""id"": ""1d2a6a08-4b73-4fdb-82d9-22fd219fd34d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Print"",
                    ""type"": ""Button"",
                    ""id"": ""37d18a90-a39d-43c6-b0d1-69d617bff8a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Leave"",
                    ""type"": ""Button"",
                    ""id"": ""9c9eeab1-0b1d-41e7-a1b6-4b7a7c97db8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d2655798-5aed-4f57-bf99-96e6d1dda7cd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleRecipe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""05a6d471-310d-4272-a9b3-7d947b8f9a4f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CycleRecipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9d1a2886-eafe-442b-bd61-3d9ee136d464"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CycleRecipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""42a3de26-a469-4ddd-98eb-83972f054964"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Print"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce195850-8707-4eba-a6a8-30b8ed55ab17"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Leave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_MovementAxis = m_Default.FindAction("MovementAxis", throwIfNotFound: true);
        m_Default_CameraAxis = m_Default.FindAction("CameraAxis", throwIfNotFound: true);
        m_Default_Interact = m_Default.FindAction("Interact", throwIfNotFound: true);
        // Printer
        m_Printer = asset.FindActionMap("Printer", throwIfNotFound: true);
        m_Printer_CycleRecipe = m_Printer.FindAction("CycleRecipe", throwIfNotFound: true);
        m_Printer_Print = m_Printer.FindAction("Print", throwIfNotFound: true);
        m_Printer_Leave = m_Printer.FindAction("Leave", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_MovementAxis;
    private readonly InputAction m_Default_CameraAxis;
    private readonly InputAction m_Default_Interact;
    public struct DefaultActions
    {
        private @AC_CharacterInputActions m_Wrapper;
        public DefaultActions(@AC_CharacterInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementAxis => m_Wrapper.m_Default_MovementAxis;
        public InputAction @CameraAxis => m_Wrapper.m_Default_CameraAxis;
        public InputAction @Interact => m_Wrapper.m_Default_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @MovementAxis.started += instance.OnMovementAxis;
            @MovementAxis.performed += instance.OnMovementAxis;
            @MovementAxis.canceled += instance.OnMovementAxis;
            @CameraAxis.started += instance.OnCameraAxis;
            @CameraAxis.performed += instance.OnCameraAxis;
            @CameraAxis.canceled += instance.OnCameraAxis;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @MovementAxis.started -= instance.OnMovementAxis;
            @MovementAxis.performed -= instance.OnMovementAxis;
            @MovementAxis.canceled -= instance.OnMovementAxis;
            @CameraAxis.started -= instance.OnCameraAxis;
            @CameraAxis.performed -= instance.OnCameraAxis;
            @CameraAxis.canceled -= instance.OnCameraAxis;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);

    // Printer
    private readonly InputActionMap m_Printer;
    private List<IPrinterActions> m_PrinterActionsCallbackInterfaces = new List<IPrinterActions>();
    private readonly InputAction m_Printer_CycleRecipe;
    private readonly InputAction m_Printer_Print;
    private readonly InputAction m_Printer_Leave;
    public struct PrinterActions
    {
        private @AC_CharacterInputActions m_Wrapper;
        public PrinterActions(@AC_CharacterInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CycleRecipe => m_Wrapper.m_Printer_CycleRecipe;
        public InputAction @Print => m_Wrapper.m_Printer_Print;
        public InputAction @Leave => m_Wrapper.m_Printer_Leave;
        public InputActionMap Get() { return m_Wrapper.m_Printer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrinterActions set) { return set.Get(); }
        public void AddCallbacks(IPrinterActions instance)
        {
            if (instance == null || m_Wrapper.m_PrinterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PrinterActionsCallbackInterfaces.Add(instance);
            @CycleRecipe.started += instance.OnCycleRecipe;
            @CycleRecipe.performed += instance.OnCycleRecipe;
            @CycleRecipe.canceled += instance.OnCycleRecipe;
            @Print.started += instance.OnPrint;
            @Print.performed += instance.OnPrint;
            @Print.canceled += instance.OnPrint;
            @Leave.started += instance.OnLeave;
            @Leave.performed += instance.OnLeave;
            @Leave.canceled += instance.OnLeave;
        }

        private void UnregisterCallbacks(IPrinterActions instance)
        {
            @CycleRecipe.started -= instance.OnCycleRecipe;
            @CycleRecipe.performed -= instance.OnCycleRecipe;
            @CycleRecipe.canceled -= instance.OnCycleRecipe;
            @Print.started -= instance.OnPrint;
            @Print.performed -= instance.OnPrint;
            @Print.canceled -= instance.OnPrint;
            @Leave.started -= instance.OnLeave;
            @Leave.performed -= instance.OnLeave;
            @Leave.canceled -= instance.OnLeave;
        }

        public void RemoveCallbacks(IPrinterActions instance)
        {
            if (m_Wrapper.m_PrinterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPrinterActions instance)
        {
            foreach (var item in m_Wrapper.m_PrinterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PrinterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PrinterActions @Printer => new PrinterActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnMovementAxis(InputAction.CallbackContext context);
        void OnCameraAxis(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IPrinterActions
    {
        void OnCycleRecipe(InputAction.CallbackContext context);
        void OnPrint(InputAction.CallbackContext context);
        void OnLeave(InputAction.CallbackContext context);
    }
}
